services:
  postgres:
    image: postgres:16.9
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - ./postgres/.env
  graphql-engine:
    image: hasura
    build:
      context: ./hasura
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: always
    env_file:
      - ./hasura/.env
  backend:
    image: backend
    build:
      context: ./backend
      target: development
    command: npm run start:debug
    env_file:
      - ./backend/.env
    ports:
      - 3000:3000
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
  dashboard:
    image: dashboard
    build:
      context: ./dashboard
    ports:
      - "3001:5173"
    volumes:
      - ./dashboard:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
volumes:
  db_data:
