# fly.toml app configuration file generated for credit-card-fraud-challenge-hasura on 2025-07-28T05:22:35Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'credit-card-fraud-challenge-hasura'
primary_region = 'sea'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
